package demo;

import java.awt.Container;
import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;

/**
 *
 * @author Sraboni
 */
public class AdoptionAppealUI extends javax.swing.JFrame {
    private DisplayManager mgr;
    /**
     * Creates new form AdoptionAppealUI
     */
    public AdoptionAppealUI(DisplayManager mgr) {
        this.mgr = mgr;
        initComponents();
        //mgr.initAA("adoptappeal.csv");
        AAppeal1.setVisible(true);
        AAppeal2.setVisible(false);
        AAppeal3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AAppeal3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        AAppeal2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        AAppeal1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.setForeground(Color.GREEN);
        jButton2 = new javax.swing.JButton();
        jButton2.setForeground(Color.RED);
        jTextField3 = new javax.swing.JTextField();
        jError1 = new javax.swing.JLabel();
        jError2 = new javax.swing.JLabel();
        jError3 = new javax.swing.JLabel();
        jError4 = new javax.swing.JLabel();
        jError5 = new javax.swing.JLabel();
        jError6 = new javax.swing.JLabel();
        jError7 = new javax.swing.JLabel();
        jComboBox0 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel13.setText("Your APPEAL");

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 26)); // NOI18N
        jLabel14.setText("For ADOPTION");

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel15.setText("Are You SURE");

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei", 0, 26)); // NOI18N
        jLabel16.setText("To DISCHARGE");

        jButton4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton4.setText("Go Back");
        jButton4.setAlignmentY(0.0F);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei", 1, 28)); // NOI18N
        jLabel17.setText("?!");

        javax.swing.GroupLayout AAppeal3Layout = new javax.swing.GroupLayout(AAppeal3);
        AAppeal3.setLayout(AAppeal3Layout);
        AAppeal3Layout.setHorizontalGroup(
            AAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AAppeal3Layout.createSequentialGroup()
                .addGroup(AAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AAppeal3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel15))
                    .addGroup(AAppeal3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AAppeal3Layout.createSequentialGroup()
                .addGroup(AAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AAppeal3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(AAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)))
                    .addGroup(AAppeal3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton4))
                    .addGroup(AAppeal3Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel17))
                    .addGroup(AAppeal3Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel13)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        AAppeal3Layout.setVerticalGroup(
            AAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AAppeal3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel15)
                .addGap(51, 51, 51)
                .addComponent(jLabel16)
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addGap(49, 49, 49)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(33, 33, 33)
                .addComponent(jButton5)
                .addGap(44, 44, 44))
        );

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel9.setText("Your APPEAL");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 26)); // NOI18N
        jLabel10.setText("For ADOPTION");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel11.setText("Has Been Posted");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 28)); // NOI18N
        jLabel12.setText("SUCCESSFULLY");

        jButton3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AAppeal2Layout = new javax.swing.GroupLayout(AAppeal2);
        AAppeal2.setLayout(AAppeal2Layout);
        AAppeal2Layout.setHorizontalGroup(
            AAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AAppeal2Layout.createSequentialGroup()
                .addGroup(AAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AAppeal2Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton3))
                    .addGroup(AAppeal2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(AAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)))
                    .addGroup(AAppeal2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel12))
                    .addGroup(AAppeal2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel9)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        AAppeal2Layout.setVerticalGroup(
            AAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AAppeal2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel9)
                .addGap(42, 42, 42)
                .addComponent(jLabel10)
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addGap(82, 82, 82)
                .addComponent(jButton3)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel1.setText("Appeal for Adoption");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel2.setText("Select Animal :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel3.setText("Select Service Provider :");

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "NGO", "VET", "PARAVET", "GROMMER" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel4.setText("Select Location :");

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox2.setModel(new DefaultComboBoxModel(new String[] {"--Select--", "Kolkata", "Dum Dum", "Salt Lake", "New Town", "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur (South Dinajpur)", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 Parganas", "Paschim Medinipur (West Medinipur)", "Paschim (West) ", "Burdwan (Bardhaman)", "Purba Burdwan (Bardhaman)", "Purba Medinipur (East Medinipur)", "Purulia", "South 24 Parganas", "Uttar Dinajpur (North Dinajpur)"}));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel5.setText("Enter Animal's Age :");

        jTextField2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel6.setText("Enter Needs :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel7.setText("Enter Disease (if any) :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel8.setText("Select Criteria :");

        jComboBox3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox3.setModel(new DefaultComboBoxModel(new String[] {"--Select--", "NA", "Open", "Semi-open", "Closed", "Domestic", "International"}));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("Appeal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jError1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError1.setForeground(new java.awt.Color(255, 0, 0));

        jError2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError2.setForeground(new java.awt.Color(255, 0, 0));

        jError3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError3.setForeground(new java.awt.Color(255, 0, 0));

        jError4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError4.setForeground(new java.awt.Color(255, 0, 0));

        jError5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError5.setForeground(new java.awt.Color(255, 0, 0));

        jError6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError6.setForeground(new java.awt.Color(255, 0, 0));

        jError7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError7.setForeground(new java.awt.Color(255, 0, 0));

        jComboBox0.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox0.setModel(new DefaultComboBoxModel(new String[] {"--Select--", "Bird", "Cat", "Dog", "Hamster", "Rabbit", "Fish"}));
        jComboBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AAppeal1Layout = new javax.swing.GroupLayout(AAppeal1);
        AAppeal1Layout.setHorizontalGroup(
        	AAppeal1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(AAppeal1Layout.createSequentialGroup()
        			.addGap(58)
        			.addComponent(jButton1)
        			.addPreferredGap(ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        			.addGap(56))
        		.addGroup(AAppeal1Layout.createSequentialGroup()
        			.addContainerGap(36, Short.MAX_VALUE)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2)
        				.addComponent(jLabel3)
        				.addComponent(jLabel4)
        				.addComponent(jLabel5)
        				.addComponent(jLabel6)
        				.addComponent(jLabel7)
        				.addComponent(jLabel8))
        			.addGap(23)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jError7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jError5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jError2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jComboBox1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jComboBox2, 0, 200, Short.MAX_VALUE)
        				.addComponent(jTextField2)
        				.addComponent(jComboBox3, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jTextField4)
        				.addComponent(jTextField3)
        				.addComponent(jError1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jError3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jError4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jError6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jComboBox0, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(29))
        		.addGroup(AAppeal1Layout.createSequentialGroup()
        			.addContainerGap(108, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(106))
        );
        AAppeal1Layout.setVerticalGroup(
        	AAppeal1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(AAppeal1Layout.createSequentialGroup()
        			.addGap(24)
        			.addComponent(jLabel1)
        			.addGap(34)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jComboBox0, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError1, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError2, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        			.addGap(26)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError3, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
        			.addGap(21)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError4, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        			.addGap(29)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError5, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
        			.addGap(23)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError6, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
        			.addGap(25)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError7, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
        			.addGap(31)
        			.addGroup(AAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton2))
        			.addContainerGap())
        );
        AAppeal1.setLayout(AAppeal1Layout);

        jError1.getAccessibleContext().setAccessibleName("jError1");
        jError2.getAccessibleContext().setAccessibleName("jError2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(AAppeal1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		.addComponent(AAppeal2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		.addComponent(AAppeal3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(AAppeal1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(23))
        		.addComponent(AAppeal2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addComponent(AAppeal3, GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AAppeal1.setVisible(false);
        AAppeal3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox0.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 0 || jComboBox2.getSelectedIndex() == 0 || jTextField2.getText().isEmpty() || this.checkAge() == false || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jComboBox3.getSelectedIndex() == 0)
        {
            if(jComboBox0.getSelectedIndex() == 0)
                this.jError1.setText("*Please Select Animal");
            
            if(jComboBox1.getSelectedIndex() == 0)
                this.jError2.setText("*Please Select Service Provider");
            
            if(jComboBox2.getSelectedIndex() == 0)
                this.jError3.setText("*Please Select Location");
            
            if(jTextField2.getText().isEmpty())
                this.jError4.setText("*Please Enter Age");
            else
                this.checkAge();
            
            if(jTextField3.getText().isEmpty())
                this.jError5.setText("*Please Enter Need");
            else
                this.jError5.setText("");
            
            if(jTextField4.getText().isEmpty())
                this.jError6.setText("*Please Enter Disease Name otherwise NA");
            else
                this.jError6.setText("");
            
            if(jComboBox3.getSelectedIndex() == 0)
                this.jError7.setText("*Please Select Adoption Criteria");
        }
        else
        {
            this.jError4.setText("");
            this.jError5.setText("");
            this.jError6.setText("");
            AAppeal1.setVisible(false);
            String animal = null, location = null, needs = null, diseases = null, criteria = null, spUsername = null;
            int age = 0;
            animal = (String) jComboBox0.getSelectedItem();
            spUsername = (String) jComboBox1.getSelectedItem();
            location = (String) jComboBox2.getSelectedItem();
            age = Integer.parseInt(jTextField2.getText());
            needs = jTextField3.getText();
            diseases = jTextField4.getText();
            criteria = (String) jComboBox3.getSelectedItem();
            mgr.getAppealManager().addAdoptionAppeal("AdoptAppeal.csv", animal, spUsername, age, location, needs, diseases, criteria);
            AAppeal2.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton3.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AAppeal3.setVisible(false);
        AAppeal1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton5.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox0ActionPerformed
        // TODO add your handling code here:
        if(jComboBox0.getSelectedIndex() == 0)
            this.jError1.setText("*Please Select Animal");
        else
            this.jError1.setText("");
    }//GEN-LAST:event_jComboBox0ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == 0)
            this.jError2.setText("*Please Select Service Provider");
        else
            this.jError2.setText("");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex() == 0)
            this.jError3.setText("*Please Select Location");
        else
            this.jError3.setText("");
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedIndex() == 0)
            this.jError7.setText("*Please Select Criteria");
        else
            this.jError7.setText("");
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private boolean checkAge(){
        try{
            int x = Integer.parseInt(jTextField2.getText());
            if(x <= 0 || x >= 20){
                this.jError4.setText("*Invalid Age. Age Limit 1-20");
                return false;
            }
            else{
                this.jError4.setText("");
                return true;
            }
        }
        catch (NumberFormatException e){
            this.jError4.setText("*Invalid. Enter Digit Only");
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AAppeal1;
    private javax.swing.JPanel AAppeal2;
    private javax.swing.JPanel AAppeal3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox0;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jError1;
    private javax.swing.JLabel jError2;
    private javax.swing.JLabel jError3;
    private javax.swing.JLabel jError4;
    private javax.swing.JLabel jError5;
    private javax.swing.JLabel jError6;
    private javax.swing.JLabel jError7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
}
