package AWS;


import java.awt.Container;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sraboni
 */
public class AdoptionAppealUI extends javax.swing.JFrame {
    private DisplayManager mgr;
    /**
     * Creates new form AdoptionAppealUI
     */
    public AdoptionAppealUI(DisplayManager mgr) {
        this.mgr = mgr;
        initComponents();
        AAppeal1.setVisible(true);
        AAppeal2.setVisible(false);
        AAppeal3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AAppeal1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jError1 = new javax.swing.JLabel();
        jError2 = new javax.swing.JLabel();
        jError3 = new javax.swing.JLabel();
        jError4 = new javax.swing.JLabel();
        jError5 = new javax.swing.JLabel();
        jError6 = new javax.swing.JLabel();
        jError7 = new javax.swing.JLabel();
        jComboBox0 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        AAppeal2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        AAppeal3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animal Welfare System");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png")).getImage());

        AAppeal1.setMaximumSize(new java.awt.Dimension(929, 610));
        AAppeal1.setMinimumSize(new java.awt.Dimension(929, 610));
        AAppeal1.setPreferredSize(new java.awt.Dimension(929, 610));
        AAppeal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APPEAL FOR ADOPTION");
        AAppeal1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 310, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/animal.png"))); // NOI18N
        jLabel2.setText("Select Animal :");
        AAppeal1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sp2.png"))); // NOI18N
        jLabel3.setText("Select Service Provider :");
        AAppeal1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, 30));

        jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "NGO", "VET", "PARAVET", "GROMMER" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        AAppeal1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 420, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/location5.png"))); // NOI18N
        jLabel4.setText("Select Location :");
        AAppeal1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 140, 20));

        jComboBox2.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur (South Dinajpur)", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 Parganas", "Paschim Medinipur (West Medinipur)", "Paschim (West) ", "Burdwan (Bardhaman)", "Purba Burdwan (Bardhaman)", "Purba Medinipur (East Medinipur)", "Purulia", "South 24 Parganas", "Uttar Dinajpur (North Dinajpur)" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        AAppeal1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 420, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/age.png"))); // NOI18N
        jLabel5.setText("Enter Animal's Age :");
        AAppeal1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, 20));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 0));
        AAppeal1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 420, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/needs.png"))); // NOI18N
        jLabel6.setText("Enter Needs :");
        AAppeal1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 110, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disease.png"))); // NOI18N
        jLabel7.setText("Enter Disease (if any) :");
        AAppeal1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 170, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/criteria.png"))); // NOI18N
        jLabel8.setText("Select Criteria :");
        AAppeal1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 140, 20));

        jComboBox3.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Open", "Semi-open", "Closed", "Domestic", "International" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        AAppeal1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 420, 20));

        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 0));
        AAppeal1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 420, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yes.png"))); // NOI18N
        jButton1.setText("Appeal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AAppeal1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AAppeal1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));

        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 0));
        AAppeal1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 420, 20));

        jError1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError1.setForeground(new java.awt.Color(255, 0, 0));
        AAppeal1.add(jError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 420, 20));
        jError1.getAccessibleContext().setAccessibleName("jError1");

        jError2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError2.setForeground(new java.awt.Color(255, 0, 0));
        AAppeal1.add(jError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 420, 20));
        jError2.getAccessibleContext().setAccessibleName("jError2");

        jError3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError3.setForeground(new java.awt.Color(255, 0, 0));
        AAppeal1.add(jError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 420, 20));

        jError4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError4.setForeground(new java.awt.Color(255, 0, 0));
        AAppeal1.add(jError4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 420, 20));

        jError5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError5.setForeground(new java.awt.Color(255, 0, 0));
        AAppeal1.add(jError5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 420, 20));

        jError6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError6.setForeground(new java.awt.Color(255, 0, 0));
        AAppeal1.add(jError6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 420, 20));

        jError7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError7.setForeground(new java.awt.Color(255, 0, 0));
        AAppeal1.add(jError7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 420, 20));

        jComboBox0.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox0.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox0.setForeground(new java.awt.Color(255, 255, 0));
        jComboBox0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Bird", "Cat", "Cow", "Dog", "Fish", "Rabbit" }));
        jComboBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox0ActionPerformed(evt);
            }
        });
        AAppeal1.add(jComboBox0, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 420, 20));

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator1.setForeground(new java.awt.Color(204, 0, 0));
        AAppeal1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 930, 20));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg4.png"))); // NOI18N
        AAppeal1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        AAppeal2.setPreferredSize(new java.awt.Dimension(929, 610));
        AAppeal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yes.png"))); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        AAppeal2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appeal.png"))); // NOI18N
        AAppeal2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        AAppeal3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        AAppeal3.setMinimumSize(new java.awt.Dimension(930, 1098));
        AAppeal3.setPreferredSize(new java.awt.Dimension(929, 610));
        AAppeal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton4.setText("Go Back To Appeal");
        jButton4.setAlignmentY(0.0F);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        AAppeal3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 204));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jButton5.setText("Go Back To Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        AAppeal3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 30)); // NOI18N
        jLabel9.setText("?");
        AAppeal3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 30, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/discharge.png"))); // NOI18N
        AAppeal3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AAppeal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AAppeal2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(AAppeal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AAppeal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AAppeal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(AAppeal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AAppeal1.setVisible(false);
        AAppeal3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox0.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 0 || jComboBox2.getSelectedIndex() == 0 || jTextField2.getText().isEmpty() || this.checkAge() == false || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jComboBox3.getSelectedIndex() == 0)
        {
            if(jComboBox0.getSelectedIndex() == 0)
                this.jError1.setText("*Please Select Animal");
            
            if(jComboBox1.getSelectedIndex() == 0)
                this.jError2.setText("*Please Select Service Provider");
            
            if(jComboBox2.getSelectedIndex() == 0)
                this.jError3.setText("*Please Select Location");
            
            if(jTextField2.getText().isEmpty())
                this.jError4.setText("*Please Enter Age");
            else
                this.checkAge();
            
            if(jTextField3.getText().isEmpty())
                this.jError5.setText("*Please Enter Need");
            else
                this.jError5.setText("");
            
            if(jTextField4.getText().isEmpty())
                this.jError6.setText("*Please Enter Disease Name otherwise NA");
            else
                this.jError6.setText("");
            
            if(jComboBox3.getSelectedIndex() == 0)
                this.jError7.setText("*Please Select Adoption Criteria");
        }
        else
        {
            this.jError4.setText("");
            this.jError5.setText("");
            this.jError6.setText("");
            AAppeal1.setVisible(false);
            String animal = null, location = null, needs = null, diseases = null, criteria = null, spUsername = null;
            int age = 0;
            animal = (String) jComboBox0.getSelectedItem();
            spUsername = (String) jComboBox1.getSelectedItem();
            location = (String) jComboBox2.getSelectedItem();
            age = Integer.parseInt(jTextField2.getText());
            needs = jTextField3.getText();
            diseases = jTextField4.getText();
            criteria = (String) jComboBox3.getSelectedItem();
            mgr.getAppealManager().addAdoptionAppeal("AdoptAppeal.csv", animal, spUsername, age, location, needs, diseases, criteria);
            AAppeal2.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton3.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AAppeal3.setVisible(false);
        AAppeal1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton5.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox0ActionPerformed
        // TODO add your handling code here:
        if(jComboBox0.getSelectedIndex() == 0)
            this.jError1.setText("*Please Select Animal");
        else
            this.jError1.setText("");
    }//GEN-LAST:event_jComboBox0ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == 0)
            this.jError2.setText("*Please Select Service Provider");
        else
            this.jError2.setText("");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex() == 0)
            this.jError3.setText("*Please Select Location");
        else
            this.jError3.setText("");
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedIndex() == 0)
            this.jError7.setText("*Please Select Criteria");
        else
            this.jError7.setText("");
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private boolean checkAge(){
        try{
            int x = Integer.parseInt(jTextField2.getText());
            if(x <= 0 || x >= 20){
                this.jError4.setText("*Invalid Age. Age Limit 1-20");
                return false;
            }
            else{
                this.jError4.setText("");
                return true;
            }
        }
        catch (NumberFormatException e){
            this.jError4.setText("*Invalid. Enter Digit Only");
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdoptionAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdoptionAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdoptionAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdoptionAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdoptionAppealUI(new AppealManager()).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AAppeal1;
    private javax.swing.JPanel AAppeal2;
    private javax.swing.JPanel AAppeal3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox0;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jError1;
    private javax.swing.JLabel jError2;
    private javax.swing.JLabel jError3;
    private javax.swing.JLabel jError4;
    private javax.swing.JLabel jError5;
    private javax.swing.JLabel jError6;
    private javax.swing.JLabel jError7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
