package AWS;


import java.awt.Container;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sraboni Ghosh
 */
public class DonationAppealUI extends javax.swing.JFrame {
    private DisplayManager mgr;
    /**
     * Creates new form DonationAppealUI
     */
    public DonationAppealUI(DisplayManager mgr) {
        this.mgr = mgr;
        initComponents();
        DAppeal1.setVisible(true);
        DAppeal2.setVisible(false);
        DAppeal3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DAppeal3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        DAppeal2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        DAppeal1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jError1 = new javax.swing.JLabel();
        jError2 = new javax.swing.JLabel();
        jError3 = new javax.swing.JLabel();
        jComboBox0 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animal Welfare System");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png")).getImage());

        DAppeal3.setMaximumSize(new java.awt.Dimension(929, 610));
        DAppeal3.setMinimumSize(new java.awt.Dimension(929, 610));
        DAppeal3.setPreferredSize(new java.awt.Dimension(929, 610));
        DAppeal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe Script", 1, 30)); // NOI18N
        jLabel11.setText("?");
        DAppeal3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton4.setText("Go Back To Appeal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        DAppeal3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 204));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/animal.png"))); // NOI18N
        jButton5.setText("Go Back To Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        DAppeal3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/discharge.png"))); // NOI18N
        DAppeal3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        DAppeal2.setMaximumSize(new java.awt.Dimension(929, 610));
        DAppeal2.setMinimumSize(new java.awt.Dimension(929, 610));
        DAppeal2.setPreferredSize(new java.awt.Dimension(929, 610));
        DAppeal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yes.png"))); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        DAppeal2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appeal.png"))); // NOI18N
        DAppeal2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        DAppeal1.setMaximumSize(new java.awt.Dimension(929, 610));
        DAppeal1.setMinimumSize(new java.awt.Dimension(929, 610));
        DAppeal1.setPreferredSize(new java.awt.Dimension(929, 610));
        DAppeal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("APPEAL FOR DONATION");
        DAppeal1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/amount.png"))); // NOI18N
        jLabel2.setText("Enter Amount :");
        DAppeal1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cause.png"))); // NOI18N
        jLabel3.setText("Select Cause :");
        DAppeal1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sp2.png"))); // NOI18N
        jLabel4.setText("Select Service Provider :");
        DAppeal1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 170, -1));

        jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "NGO", "VET", "PARAVET", "GROMMER" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        DAppeal1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 400, -1));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 0));
        DAppeal1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 400, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yes.png"))); // NOI18N
        jButton1.setText("Appeal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        DAppeal1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        DAppeal1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, -1, -1));

        jError1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError1.setForeground(new java.awt.Color(255, 0, 0));
        DAppeal1.add(jError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 400, 17));

        jError2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError2.setForeground(new java.awt.Color(255, 0, 0));
        DAppeal1.add(jError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 400, 20));

        jError3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError3.setForeground(new java.awt.Color(255, 0, 0));
        DAppeal1.add(jError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 400, 20));

        jComboBox0.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox0.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox0.setForeground(new java.awt.Color(255, 255, 0));
        jComboBox0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Caring", "Feeding", "Sterilisation", "Treatment", "Vaccination", "Shelter Maintenance", "Miscellaneous" }));
        jComboBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox0ActionPerformed(evt);
            }
        });
        DAppeal1.add(jComboBox0, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 400, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 0));
        DAppeal1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 930, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg4.png"))); // NOI18N
        DAppeal1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DAppeal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DAppeal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton3.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DAppeal3.setVisible(false);
        DAppeal1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton5.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DAppeal1.setVisible(false);
        DAppeal3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().isEmpty() || this.checkAmount() == false || jComboBox0.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 0)
        {
            if(jTextField2.getText().isEmpty())
                this.jError1.setText("*Please Enter Amount");
            else
                this.checkAmount();
            
            if(jComboBox0.getSelectedIndex() == 0)
                this.jError2.setText("*Please Select Cause");
            
            if(jComboBox1.getSelectedIndex() == 0)
                this.jError3.setText("*Please Select Service Provider");
        }
        else
        {
            this.jError1.setText("");
            this.jError2.setText("");
            DAppeal1.setVisible(false);
            String cause = null, spUsername = null;
            double amount = 0;
            amount = Integer.parseInt(jTextField2.getText());
            cause = (String) jComboBox0.getSelectedItem();
            spUsername = (String) jComboBox1.getSelectedItem();
            mgr.getAppealManager().addDonationAppeal("DonateAppeal.csv", amount, cause, spUsername);
            DAppeal2.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == 0)
            this.jError3.setText("*Please Select Service Provider");
        else
            this.jError3.setText("");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox0ActionPerformed
        // TODO add your handling code here:
        if(jComboBox0.getSelectedIndex() == 0)
            this.jError2.setText("*Please Select Cause");
        else
            this.jError2.setText("");
    }//GEN-LAST:event_jComboBox0ActionPerformed

    private boolean checkAmount(){
        try{
            double x = Double.parseDouble(jTextField2.getText());
            if(x <= 0 || x >= 50000){
                this.jError1.setText("*Invalid Amount. Limit upto 50000");
                return false;
            }
            else{
                this.jError1.setText("");
                return true;
            }
        }
        catch (NumberFormatException e){
            this.jError1.setText("*Invalid. Enter Digit Only");
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonationAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonationAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonationAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonationAppealUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonationAppealUI(new AppealManager()).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DAppeal1;
    private javax.swing.JPanel DAppeal2;
    private javax.swing.JPanel DAppeal3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox0;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jError1;
    private javax.swing.JLabel jError2;
    private javax.swing.JLabel jError3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
