package demo;


import java.awt.Container;
import javax.swing.JFrame;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author Sraboni
 */
public class DonationAppealUI extends javax.swing.JFrame {
    private DisplayManager mgr;
    /**
     * Creates new form DonationAppealUI
     */
    public DonationAppealUI(DisplayManager mgr) {
        this.mgr = mgr;
        initComponents();
        //mgr.initDA("donateappeal.csv");
        DAppeal1.setVisible(true);
        DAppeal2.setVisible(false);
        DAppeal3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        DAppeal3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        DAppeal2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        DAppeal1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.setForeground(Color.GREEN);
        jButton2 = new javax.swing.JButton();
        jButton2.setForeground(Color.RED);
        jError1 = new javax.swing.JLabel();
        jError2 = new javax.swing.JLabel();
        jError3 = new javax.swing.JLabel();
        jComboBox0 = new javax.swing.JComboBox<>();
        jComboBox0.setFont(new Font("Arial", Font.PLAIN, 11));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel9.setText("Are You SURE");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 26)); // NOI18N
        jLabel10.setText("To DISCHARGE");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel11.setText("Your APPEAL");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 0, 26)); // NOI18N
        jLabel12.setText("For DONATION");

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 1, 28)); // NOI18N
        jLabel13.setText("?!");

        jButton4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DAppeal3Layout = new javax.swing.GroupLayout(DAppeal3);
        DAppeal3.setLayout(DAppeal3Layout);
        DAppeal3Layout.setHorizontalGroup(
            DAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DAppeal3Layout.createSequentialGroup()
                .addGroup(DAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DAppeal3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(DAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)))
                    .addGroup(DAppeal3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel9))
                    .addGroup(DAppeal3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel11))
                    .addGroup(DAppeal3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel13))
                    .addGroup(DAppeal3Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton5))
                    .addGroup(DAppeal3Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton4)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        DAppeal3Layout.setVerticalGroup(
            DAppeal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DAppeal3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel9)
                .addGap(48, 48, 48)
                .addComponent(jLabel10)
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addGap(41, 41, 41)
                .addComponent(jLabel12)
                .addGap(42, 42, 42)
                .addComponent(jLabel13)
                .addGap(43, 43, 43)
                .addComponent(jButton4)
                .addGap(34, 34, 34)
                .addComponent(jButton5)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel5.setText("Your APPEAL");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 0, 26)); // NOI18N
        jLabel6.setText("For DONATION");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel7.setText("Has Been Posted");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 28)); // NOI18N
        jLabel8.setText("SUCCESSFULLY");

        jButton3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DAppeal2Layout = new javax.swing.GroupLayout(DAppeal2);
        DAppeal2.setLayout(DAppeal2Layout);
        DAppeal2Layout.setHorizontalGroup(
            DAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DAppeal2Layout.createSequentialGroup()
                .addGroup(DAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DAppeal2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(DAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(DAppeal2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel8))
                    .addGroup(DAppeal2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton3))
                    .addGroup(DAppeal2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel5)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        DAppeal2Layout.setVerticalGroup(
            DAppeal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DAppeal2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addGap(77, 77, 77)
                .addComponent(jButton3)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel1.setText("Appeal for Donation");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel3.setText("Enter Cause :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel4.setText("Select Service Provider :");

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "NGO", "VET", "PARAVET", "GROMMER" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("Appeal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jError1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError1.setForeground(new java.awt.Color(255, 0, 0));

        jError2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError2.setForeground(new java.awt.Color(255, 0, 0));

        jError3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jError3.setForeground(new java.awt.Color(255, 0, 0));

        jComboBox0.setModel(new DefaultComboBoxModel(new String[] {"--Select--", "Caring", "Feeding", "Sterilisation", "Treatment", "Vaccination", "Shelter Maintenance", "Miscellaneous"}));
        jComboBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox0ActionPerformed(evt);
            }
        });
        
        JLabel jLabel2 = new JLabel();
        jLabel2.setText("Enter Amount :");
        jLabel2.setFont(new Font("Times New Roman", Font.PLAIN, 11));

        javax.swing.GroupLayout DAppeal1Layout = new javax.swing.GroupLayout(DAppeal1);
        DAppeal1Layout.setHorizontalGroup(
        	DAppeal1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(DAppeal1Layout.createSequentialGroup()
        			.addGap(115)
        			.addComponent(jLabel1)
        			.addContainerGap(116, Short.MAX_VALUE))
        		.addGroup(DAppeal1Layout.createSequentialGroup()
        			.addGap(48)
        			.addGroup(DAppeal1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(DAppeal1Layout.createSequentialGroup()
        					.addGroup(DAppeal1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3)
        						.addComponent(jLabel4)
        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(DAppeal1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jTextField2)
        						.addComponent(jError1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jError2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jComboBox0, 0, 192, Short.MAX_VALUE)
        						.addComponent(jError3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(DAppeal1Layout.createSequentialGroup()
        					.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        					.addGap(190)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)))
        			.addGap(43))
        );
        DAppeal1Layout.setVerticalGroup(
        	DAppeal1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(DAppeal1Layout.createSequentialGroup()
        			.addGap(47)
        			.addComponent(jLabel1)
        			.addGap(93)
        			.addGroup(DAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError1, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
        			.addGap(44)
        			.addGroup(DAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBox0, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        			.addGap(47)
        			.addGroup(DAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jError3, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
        			.addGap(92)
        			.addGroup(DAppeal1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        			.addGap(106))
        );
        DAppeal1.setLayout(DAppeal1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DAppeal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DAppeal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DAppeal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton3.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DAppeal3.setVisible(false);
        DAppeal1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Container frame = jButton5.getParent();
            do 
                frame = frame.getParent(); 
            while (!(frame instanceof JFrame));                                      
            ((JFrame) frame).dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DAppeal1.setVisible(false);
        DAppeal3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().isEmpty() || this.checkAmount() == false || jComboBox0.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 0)
        {
            if(jTextField2.getText().isEmpty())
                this.jError1.setText("*Please Enter Amount");
            else
                this.checkAmount();
            
            if(jComboBox0.getSelectedIndex() == 0)
                this.jError2.setText("*Please Select Cause");
            
            if(jComboBox1.getSelectedIndex() == 0)
                this.jError3.setText("*Please Select Service Provider");
        }
        else
        {
            this.jError1.setText("");
            this.jError2.setText("");
            DAppeal1.setVisible(false);
            String cause = null, spUsername = null;
            double amount = 0;
            amount = Integer.parseInt(jTextField2.getText());
            cause = (String) jComboBox0.getSelectedItem();
            spUsername = (String) jComboBox1.getSelectedItem();
            mgr.getAppealManager().addDonationAppeal("DonateAppeal.csv", amount, cause, spUsername);
            DAppeal2.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == 0)
            this.jError3.setText("*Please Select Service Provider");
        else
            this.jError3.setText("");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox0ActionPerformed
        // TODO add your handling code here:
        if(jComboBox0.getSelectedIndex() == 0)
            this.jError2.setText("*Please Select Cause");
        else
            this.jError2.setText("");
    }//GEN-LAST:event_jComboBox0ActionPerformed

    private boolean checkAmount(){
        try{
            double x = Double.parseDouble(jTextField2.getText());
            if(x <= 0 || x >= 50000){
                this.jError1.setText("*Invalid Amount. Limit upto 50000");
                return false;
            }
            else{
                this.jError1.setText("");
                return true;
            }
        }
        catch (NumberFormatException e){
            this.jError1.setText("*Invalid. Enter Digit Only");
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    
    private javax.swing.JPanel DAppeal1;
    private javax.swing.JPanel DAppeal2;
    private javax.swing.JPanel DAppeal3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox0;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jError1;
    private javax.swing.JLabel jError2;
    private javax.swing.JLabel jError3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
}
